# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 19:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_comment_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 19, 0, 13, 359000, tzinfo=utc)),
        ),
    ]
